### ISSUE TITLE
API data

### ISSUE THREAD

**Issue by rramola** [rramola/RightWayRealty#5]

**Comment by CodeWithDustin** [comment]
Flex MLS api data is integrated and working and pulling from their free issue of their api. Need to get the paid version and also get with NavicaMLS for their paid version to get her real data from both.

**Comment by CodeWithDustin** [comment]
Flex MLS api data is integrated and working and pulling from their free issue of their api. Need to get the paid version and also get with NavicaMLS for their paid version to get her real data from both.
